### ISSUE TITLE
PEP-563 breaks SerializationStrategy

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [Fatal1ty/mashumaro#10]
1. `SerializationStrategy` example with `DateTimeFormats` works fine in py3.7
https://github.com/Fatal1ty/mashumaro#user-defined-classes

2. however introduction of PEP-563 via `from __future__ import annotations`
https://www.python.org/dev/peps/pep-0563/
breaks usage of `SerializationStrategy` with error trace:
```
Traceback (most recent call last):
  File ".../src/verify/code/mashu/mashu_pep563.py", line 22, in <module>
    class DateTimeFormats(DataClassDictMixin):
  File "/usr/lib/python3.7/site-packages/mashumaro/serializer/base/dict.py", line 19, in __init_subclass__
    raise exc
  File "/usr/lib/python3.7/site-packages/mashumaro/serializer/base/dict.py", line 15, in __init_subclass__
    builder.add_to_dict()
  File "/usr/lib/python3.7/site-packages/mashumaro/serializer/base/metaprogramming.py", line 163, in add_to_dict
    for fname, ftype in self.fields.items():
  File "/usr/lib/python3.7/site-packages/mashumaro/serializer/base/metaprogramming.py", line 53, in fields
    for fname, ftype in typing.get_type_hints(self.cls).items():
  File "/usr/lib/python3.7/typing.py", line 973, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/usr/lib/python3.7/typing.py", line 260, in _eval_type
    return t._evaluate(globalns, localns)
  File "/usr/lib/python3.7/typing.py", line 466, in _evaluate
    is_argument=self.__forward_is_argument__)
  File "/usr/lib/python3.7/typing.py", line 139, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
TypeError: Forward references must evaluate to types. Got <__main__.FormattedDateTime object at 0x7faec3540f60>.

```

**Comment by Andrei-Pozolotin** [comment]
perhaps a better approach is to use separate serialization annotations. i.e.:

```
@dataclass
class DateTimeFormats(DataClassDictMixin):
    @FormattedDateTime(fmt='%d%m%Y%H%M%S') 
    short:datetime
    @FormattedDateTime(fmt='%A %B %d, %Y, %H:%M:%S')
    verbose:datetime
```

**Comment by dand-oss** [comment]
from __future__ import annotations
from mashumaro import DataClassJSONMixin

@dataclass
class aClass(DataClassJSONMixin):
    mem_t: member_TT  # un declare

@dataclass
class member_TT(DataClassJSONMixin):
    pass

produces

  File "/i/t/miniconda/lib/python3.7/site-packages/mashumaro/serializer/base/dict.py", line 19, in __init_subclass__
    raise exc
  File "/i/t/miniconda/lib/python3.7/site-packages/mashumaro/serializer/base/dict.py", line 15, in __init_subclass__
    builder.add_to_dict()
  File "/i/t/miniconda/lib/python3.7/site-packages/mashumaro/serializer/base/metaprogramming.py", line 163, in add_to_dict
    for fname, ftype in self.fields.items():
  File "/i/t/miniconda/lib/python3.7/site-packages/mashumaro/serializer/base/metaprogramming.py", line 53, in fields
    for fname, ftype in typing.get_type_hints(self.cls).items():
  File "/i/t/miniconda/lib/python3.7/typing.py", line 976, in get_type_hints
    value = _eval_type(value, base_globals, localns)
  File "/i/t/miniconda/lib/python3.7/typing.py", line 263, in _eval_type
    return t._evaluate(globalns, localns)
  File "/i/t/miniconda/lib/python3.7/typing.py", line 467, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'member_TT' is not defined

**Comment by rominf** [comment]
It breaks my program in Python 3.8 too. I would consider this as a bug, but not an enhancement.

Are there plans to fix this?

**Comment by Fatal1ty** [comment]
> perhaps a better approach is to use separate serialization annotations. i.e.:
> 
> ```
> @dataclass
> class DateTimeFormats(DataClassDictMixin):
>     @FormattedDateTime(fmt='%d%m%Y%H%M%S') 
>     short:datetime
>     @FormattedDateTime(fmt='%A %B %d, %Y, %H:%M:%S')
>     verbose:datetime
> ```

The current implementation of `SerializationStrategy` is a dirty hack that won't work in Python 3.10. At this moment I'm working on [improving the customization capabilities of mashumaro](https://github.com/Fatal1ty/mashumaro/tree/datetime-parsers#using-field-metadata) and I think I can replace `SerializationStrategy` with something like this:
```python
@dataclass
class DateTimeFormats(DataClassDictMixin):
    short: datetime = field(
        default_factory=datetime.now,
        metadata={
            "serialization_strategy": FormattedDateTime("%d%m%Y%H%M%S")
        },
    )
    verbose: datetime = field(
        default_factory=datetime.now,
        metadata={
            "serialization_strategy": FormattedDateTime("%A %B %d, %Y, %H:%M:%S")
        },
    )
```

Since in would break backward compatibility I could do it in version 2.x. But anyway with upcoming changes in this library you can do the same things from the example even without `SerializationStrategy`:

```python
@dataclass
class DateTimeFormats(DataClassDictMixin):
    short: datetime = field(
        default_factory=datetime.now,
        metadata={
            'deserialize':
                lambda s: datetime.strptime(s, '%d%m%Y%H%M%S')
        }
    )
    verbose: datetime = field(
        default_factory=datetime.now,
        metadata={
            'deserialize':
                lambda s: datetime.strptime(s, '%A %B %d, %Y, %H:%M:%S')
        }
    )
```

or with `SerializationStrategy` if you'd like:

```python
@dataclass
class DateTimeFormats(DataClassDictMixin):
    short: datetime = field(
        default_factory=datetime.now,
        metadata={
            'deserialize': FormattedDateTime("%d%m%Y%H%M%S")._deserialize
        }
    )
    verbose: datetime = field(
        default_factory=datetime.now,
        metadata={
            'deserialize': FormattedDateTime("%A %B %d, %Y, %H:%M:%S")._deserialize
        }
    )
```
I haven't done `serialize` option yet but it's definitely needed and will be done soon. Also from this point of view `serialization_strategy` option in `metadata` would be no more than syntax sugar that would allow you not to define both `serialize` and `deserialize` options.

So, if anyone is interested in `SerializationStrategy` suggestions and discussion are welcome.

**Comment by Fatal1ty** [comment]
> from **future** import annotations
> from mashumaro import DataClassJSONMixin
> 
> @DataClass
> class aClass(DataClassJSONMixin):
> mem_t: member_TT # un declare
> 
> @DataClass
> class member_TT(DataClassJSONMixin):
> pass

@dand-oss your example is about another known problem with forward references https://github.com/Fatal1ty/mashumaro/issues/28

**Comment by Fatal1ty** [comment]
> It breaks my program in Python 3.8 too. I would consider this as a bug, but not an enhancement.
> 
> Are there plans to fix this?

It's not a bug but a hacky feature that should be reimplemented in another way :)

**Comment by Fatal1ty** [comment]
I changed the way how`SerializationStrategy` classes are used. @rominf you might be interested in reading README [here](https://github.com/Fatal1ty/mashumaro#serialization_strategy-option) and [here](https://github.com/Fatal1ty/mashumaro#serialization_strategy-config-option). At the moment these changes are in the master branch but I will release 2.0 version soon since it's not backward compatible.

**Comment by Fatal1ty** [comment]
The new changes are in 2.0 now.
