### ISSUE TITLE
Incosistency in using aliases in JSON schema

### ISSUE THREAD

**Issue by bprus** [Fatal1ty/mashumaro#101]
* mashumaro version: 3.6
* Python version: 3.9
* Operating System: macOS

### Description

Introducing JSON schema generation is great. I've been waiting for it for some time.
However, I found an issue with the current implementation in the way aliases are being handled. In some parts of the schema, aliases are used (properties), but in some parts (required), they are not.

I expect aliases to be used everywhere, either by default or by a parameter to tell if they should be used.

### What I Did

```
import dataclasses
import json

from mashumaro.config import BaseConfig
from mashumaro.jsonschema import build_json_schema
from mashumaro.mixins.orjson import DataClassORJSONMixin


@dataclasses.dataclass
class MashumaroSchema(DataClassORJSONMixin):
    input_config: str
    b: int

    class Config(BaseConfig):
        serialize_by_alias = True
        omit_none = True
        aliases = {"input_config": "inputConfig"}


example = {
    "inputConfig": "some string",
    "b": 2,
}

schema = build_json_schema(MashumaroSchema).to_dict()
print(json.dumps(schema, indent=4))
```

And the output is:

```
{
    "type": "object",
    "title": "MashumaroSchema",
    "properties": {
        "inputConfig": { <<-- here the alias is used
            "type": "string"
        },
        "b": {
            "type": "integer"
        }
    },
    "additionalProperties": false,
    "required": [
        "input_config", <<-- here the alias is not used
        "b"
    ]
}
```

**Comment by Fatal1ty** [comment]
Hi @bprus 

First of all, thank you for the warm welcome of this new feature ❤️ I put a lot of effort into it, so I am very happy with such a quick feedback. As expected, some errors may come to light at the beginning, but all of them will eventually be fixed. Good news is that it's easy to fix this aliases thing and I'll do it today or at least tomorrow. I also think it's worth waiting some time before releasing a patch in case something else pops up.

**Comment by Fatal1ty** [comment]
Fixed in master branch

**Comment by bprus** [comment]
Great, thank you very much for the quick response!
