### ISSUE TITLE
JSON Schema generator doesn't honor `default_factory`

### ISSUE THREAD

**Issue by mishamsk** [Fatal1ty/mashumaro#114]
* mashumaro version: 3.7
* Python version: 3.11 (but 3.10 is the same)
* Operating System: macOS Ventura

### Description

See the full code and output below. When using default value, directly or via `field(default=...)` the schema correctly recognizes the field as not required. But it doesn't work with `default_factory` unfortunately.

Shall I open a PR?

### What I Did

```
import json
from dataclasses import dataclass, field
from functools import partial

from mashumaro import DataClassDictMixin
from mashumaro.jsonschema import build_json_schema


@dataclass
class Foo(DataClassDictMixin):
    bar: frozenset[str] = field(default_factory=frozenset)


print(build_json_schema(Foo).to_json(encoder=partial(json.dumps, indent=2)))
# {
#   "type": "object",
#   "title": "Foo",
#   "properties": {
#     "bar": {
#       "type": "array",
#       "items": {
#         "type": "string"
#       },
#       "uniqueItems": true
#     }
#   },
#   "additionalProperties": false,
#   "required": [
#     "bar"
#   ]
# }

```

**Comment by Fatal1ty** [comment]
@mishamsk 

Thank you for paying attention to this! Yes, please, go ahead and open a PR. I will review it as soon as possible.

**Comment by mishamsk** [comment]
@Fatal1ty #122
