### ISSUE TITLE
Get errors on "from_dict": <class>.__init__() got multiple values for argument 'resource_type'

### ISSUE THREAD

**Issue by gshank** [Fatal1ty/mashumaro#118]
* mashumaro version: 3.8
* Python version: 3.10
* Operating System: MacOS

### Description

dbt Core: https://github.com/dbt-labs/dbt-core

I tested with 3.8 and got a lot of errors from a bunch of related classes that we distinguish on the field "resource_type". 
E   TypeError: AnalysisNode.__init__() got multiple values for argument 'resource_type'

Because some of these classes only differ in the value of the resource_type field, we've had to use a _deserialize method to distinguish among them: https://github.com/dbt-labs/dbt-core/blob/main/core/dbt/contracts/graph/nodes.py#L381C16-L381C16

But now it's not even getting to that.

### What I Did

```
Change mashumaro version to 3.8 and run pytest tests/unit.
```
If there's something that I can do to help diagnose, let me know.

**Comment by Fatal1ty** [comment]
@gshank 

Thank you for finding the bug so quickly. It's related to the latest optimisations.

All your unit tests are now passed, so I can release hotfix 3.8.1 now but if you have something else to check, I will wait for it. Just let me know.

> Change mashumaro version to 3.8 and run pytest tests/unit.

Next time I will run these tests before release, they are very useful.

**Comment by Fatal1ty** [comment]
Fixed in [3.8.1](https://github.com/Fatal1ty/mashumaro/releases/tag/v3.8.1)

**Comment by gshank** [comment]
Thanks so much for the new release! I'm updating right now. I'll be using some of the new functionality in the next few weeks.

It would be great to have you run the tests before releasing. We'd like to unpin the mashumaro release but haven't been able to in the past.
