### ISSUE TITLE
Allow customizing additionalProperties in jsonschemas

### ISSUE THREAD

**Issue by gshank** [Fatal1ty/mashumaro#123]
**Is your feature request related to a problem? Please describe.**
We have some classes for which we set additionalProperties=True in the jsonschema. Would it be possible to allow setting that in the embedded Config class?

**Describe the solution you'd like**
Also accept an additionalProperties key when the "properties" key is set from json_schema in the Config

**Describe alternatives you've considered**
Can set it directly in the jsonschema object, but we have a lot of nested classes so this gets messay.

**Comment by Fatal1ty** [comment]
Will it suit you if we support overriding "additionalProperties" in Config?

```python
@dataclass
class MyClass(DataClassDictMixin):
    foo: str

    class Config(BaseConfig):
        json_schema = {
            "additionalProperties": True,
        }
```

```json
{
    "type": "object",
    "title": "MyClass",
    "properties": {
        "foo": {
            "type": "string"
        }
    },
    "additionalProperties": false,
    "required": [
        "foo"
    ]
}
```

> Also accept an additionalProperties key when the "properties" key is set from json_schema in the Config

Please note that the "properties" key is currently used only for overriding schemas for existing dataclass fields, so if you add additional keys in "properties", they will be ignored. Let me know if you need to have additional keys added to JSON Schema. If this is a case, I may be wrong but setting "additionalProperties" to True would seem to be redundant.

**Comment by Fatal1ty** [comment]
@gshank

Thank you by the way for your contribution to the development of JSON Schema functionality. I would also like to wait for you to gather as much as possible JSON Schema issues to work on them together for the following release.

**Comment by gshank** [comment]
Yes, the way you're suggesting is fine. That's what I've done locally to get it working. I'm making local changes to mashumaro to get it all working so that I can provide tickets for everything. I have the unit tests working, and now I'm going to work on the functional tests. I'll update the other ticket with what I've done for that...
