### ISSUE TITLE
Enable generating jsonschema field restrictions

### ISSUE THREAD

**Issue by gshank** [Fatal1ty/mashumaro#124]
**Is your feature request related to a problem? Please describe.**
We would like to convert from our current forked jsonschema generation package (https://github.com/dbt-labs/hologram) to using mashumaro's jsonschema generation. One of the features that we're currently using is the ability to flag fields as restricted to a particular value like this:
```resource_type: NodeType = field(metadata={"restrict": [NodeType.Model]})```

Which will product jsonschema like:
```
        "resource_type": {
          "type": "string",
          "enum": [
            "model"
          ]
        },
```

**Describe the solution you'd like**
A similar field option to enforce a value restriction. 

**Describe alternatives you've considered**
Lots of custom json_schema properties. But that gets complicated because it's not easy to coordinate multiple changes to the embedded Config object. It would be easier if we could specify custom jsonschema on the field itself.

**Comment by Fatal1ty** [comment]
Can you use [`Literal`](https://docs.python.org/3/library/typing.html#typing.Literal) for value restriction? It will make your model cleaner and add ["enum"](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-enum) or ["const"](https://json-schema.org/draft/2020-12/json-schema-validation.html#name-const) (if only one particular value is allowed) to JSON Schema. Note that it will also limit deserialization to the allowed values only.

```python
from enum import Enum
from dataclasses import dataclass
from typing import Literal
from mashumaro import DataClassDictMixin
from mashumaro.jsonschema import build_json_schema


class NodeType(Enum):
    FOO = "foo"
    BAR = "bar"
    BAZ = "baz"

@dataclass
class MyClass(DataClassDictMixin):
    resource_type: Literal[NodeType.FOO, NodeType.BAR]


print(build_json_schema(MyClass).to_json())
```

```json
{
    "type": "object",
    "title": "MyClass",
    "properties": {
        "resource_type": {
            "enum": [
                "foo",
                "bar"
            ]
        }
    },
    "additionalProperties": false,
    "required": [
        "resource_type"
    ]
}
```

**Comment by gshank** [comment]
The "restrict" functionality in hologram was kind of complicated to implement, so instead I just added the ability to set a "json_schema" key in the field metadata for now, but I'll try the Literal thing and see how it works.

There was another case that I also used the "json_schema" metadata key for, and that was using a pattern, like:
```
    name: Identifier = field(
        metadata={"json_schema": {"type": "string", "pattern": r"^[^\d\W]\w*$"}}
    )
```

Is there another way to do this?

In a general way, it wasn't always easy to set individual properties in the "json_schema" config, because since it's a dictionary if there is anything set in a parent Config it has to be included in a the child Config.

**Comment by gshank** [comment]
Oh, just wanted to say that we do a lot of converting from yaml dictionary field names with dashes to fields with underscores (in python) and fields with dashes in the jsonschemas and the "alias" functionality was a much cleaner way to handle that.

**Comment by gshank** [comment]
Using Literal worked well for those fields.

**Comment by Fatal1ty** [comment]
> There was another case that I also used the "json_schema" metadata key for, and that was using a pattern, like:
> 
> ```
>     name: Identifier = field(
>         metadata={"json_schema": {"type": "string", "pattern": r"^[^\d\W]\w*$"}}
>     )
> ```
> 
> Is there another way to do this?

Yes, you can use wrappers from `mashumaro.jsonschema.annotations`:

```python
from mashumaro.jsonschema.annotations import Pattern

name: Annotated[Identifier, Pattern(r"^[^\d\W]\w*$")]
```

**Comment by Fatal1ty** [comment]
> Oh, just wanted to say that we do a lot of converting from yaml dictionary field names with dashes to fields with underscores (in python) and fields with dashes in the jsonschemas and the "alias" functionality was a much cleaner way to handle that.

Happy to hear that!

**Comment by gshank** [comment]
I've gotten the code working using the Annotations, which really work very nicely. I can imagine situations that they might not handle, but if that every comes up we can deal with it. I'm looking at the final output now and if anything comes up there I will open a new ticket.
