### ISSUE TITLE
When using "all_refs=True" to generate a jsonschema, validation fails because the top-level object has invalid reference url

### ISSUE THREAD

**Issue by gshank** [Fatal1ty/mashumaro#126]
* mashumaro version: latest
* Python version: 3.10
* Operating System: MacOS

### Description

I have the conversion from our old jsonschema generation app (hologram) to mashumaro working okay without the "all_refs" parameter turned on, but that makes the generated jsonschema very large. When I turn on "all_refs", it generates a much smaller jsonschema, but validation fails because the top-level object is a ref.

### What I Did

If you look at https://github.com/dbt-labs/dbt-core/pull/8132/, the schemas/dbt/manifest/v11.json file was generated from mashumaro (it's big and might not load in the browser). The previous generated file was schemas/dbt/manifest/v10.json, for comparison purposes.

When I modify core/dbt/dataclass_schemas.py, dbtClassMixin.json_schema to use "all_refs=True" to the "build_json_schema" call, the generated schema (added to the schemas directory by `scripts/collect-artifact-schema.py --path schemas --artifact manifest`) fails the schema tests (tests/functional/artifacts) with the error message: jsonschema.exceptions.RefResolutionError: Unresolvable JSON pointer: 'defs/WritableManifest'

The WritableManifest is the top-level object that I am creating the jsonschema for, so my guess is that the base object cannot be a ref, but this is not my area of expertise. Let me know if I should try to create a test case.

**Comment by Fatal1ty** [comment]
Hey @gshank 

I merged https://github.com/Fatal1ty/mashumaro/pull/130, so if everything works now, let me know and I prepare a release.
