### ISSUE TITLE
collections.OrderedDict is not hashable

### ISSUE THREAD

**Issue by hhcs9527** [Fatal1ty/mashumaro#133]
* mashumaro version: 3.8.1
* Python version: 3.11 / 3.10
* Operating System: Ubuntu 20.04

### Description

1. Try to run the following code
2. it keeps showing `TypeError: unhashable type: 'collections.OrderedDict'`, but the readme shows it supports this type

### What I Did

```python
import json
from enum import Enum
from typing import List, Any, Union, Generic, TypeVar, Tuple, cast, Optional, Annotated, OrderedDict, Type
import typing
import collections
from dataclasses import dataclass, field
from dataclasses_json import dataclass_json, DataClassJsonMixin
from mashumaro.mixins.json import DataClassJSONMixin
from mashumaro.types import SerializationStrategy



def kwtypes(**kwargs) -> OrderedDict[str, Type]:
    """
    This is a small helper function to convert the keyword arguments to an OrderedDict of types.

    .. code-block:: python

        kwtypes(a=int, b=str)
    """
    d = collections.OrderedDict()
    for k, v in kwargs.items():
        d[k] = v
    return d

@dataclass
class test(DataClassJSONMixin):
    b: typing.List[Annotated[int, "parquet"]]
    c: typing.Dict[str, Annotated[int, kwtypes(Name=str, Age=int)]]
```

Thanks for the help!

**Comment by Fatal1ty** [comment]
@hhcs9527

Thank you for opening this issue. This is definitely a bug related to how `Annotated` types are handled. Let me debug it and I'll fix it soon.

**Comment by Fatal1ty** [comment]
Hey @hhcs9527 

I merged the fix, you can take a look.

**Comment by hhcs9527** [comment]
Hi,
@Fatal1ty thanks for the quick fix.
Should I do something to get the latest version of code? I installed it from pip

**Comment by Fatal1ty** [comment]
I’m going to make a new release this week, so if you find another issue, it will most likely be fixed in it. Until then you can install mashumaro from git:
```
pip install git+https://github.com/Fatal1ty/mashumaro
```

**Comment by hhcs9527** [comment]
Thanks for the explanation, so I can expect this change will be in 
pip install version with 3.8.2? 

Thanks.

**Comment by Fatal1ty** [comment]
@hhcs9527 it will be 3.9

**Comment by hhcs9527** [comment]
Thanks for the notification!
Is there an expected release date?

**Comment by Fatal1ty** [comment]
> Thanks for the notification!
> Is there an expected release date?

I'm waiting for @gshank to answer on another issue but in any case it won't be later than Thursday.

**Comment by hhcs9527** [comment]
Thanks for the response.
