### ISSUE TITLE
Support Union type

### ISSUE THREAD

**Issue by diegoferigo** [Fatal1ty/mashumaro#21]
I read in the TODO list that the support of Union types is planned. Is there any timeline?

Example use case:

```python
@dataclass 
class CustomShape(DataClassYAMLMixin):
    name: str
    num_corners: int

@dataclass
class ShapeCollection(DataClassYAMLMixin):
    shapes: List[Union[str, CustomShape]]
```

```yaml
# shapes.yaml
shapes:
  - triangle
  - name: square
    num_corners: 4
```

Expected parsed structure:

```python
with open(file="shapes.yaml", mode='r') as f:
    shapes: ShapeCollection = ShapeCollection.from_yaml(data=f)

print(shapes)
# ShapeCollection(shapes=["triangle, CustomShape(name=square, num_corners: 4)"])
```

(btw: congrats for the project, it makes the most out from the combination of dataclasses and YAML)

**Comment by Fatal1ty** [comment]
Unfortunately, I can't say when I will add Unions support  because I have less time on this project than before. But I always keep it in mind. Let this issue be opened.

**Comment by diegoferigo** [comment]
Great! Thanks for the prompt answer.

**Comment by Fatal1ty** [comment]
Added in 1.24 https://github.com/Fatal1ty/mashumaro/releases/tag/v1.24
