### ISSUE TITLE
Custom IntEnum dumping

### ISSUE THREAD

**Issue by waszil** [Fatal1ty/mashumaro#22]
Hi, first of all, great package, congrats!
My question is the following: I would like to achieve that an IntEnum class would be dumped as its name to yaml.
I tried the following:

```python
class Example(IntEnum, SerializableType):
    A = 1
    B = 2

    def _serialize(self):
        return {"value": self.name}

    @classmethod
    def _deserialize(cls, value):
        return Example.__members__[value["value"]]
```

However I get this exception: `TypeError: metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases`

Is there any other way to achieve this?
Thanks!

**Comment by Fatal1ty** [comment]
Thanks for this issue! Seems like a conflict of two metaclasses: EnumMeta and ABCMeta. Well, I think we don't have a reason for SerializableType to be abstract class so I will make it a regular one.

**Comment by waszil** [comment]
Wow, thanks for the fast response!

**Comment by waszil** [comment]
Indeed, I tried it by removing ABC from SerializableType, and now it works for my case.

**Comment by waszil** [comment]
Maybe is there an other way to do this? for example with custom encoder/decoders, so that the IntEnum class itself does not need to be altered?

**Comment by Fatal1ty** [comment]
> Indeed, I tried it by removing ABC from SerializableType, and now it works for my case.

I made this in 1.13. Please, check whether it solves this problem.

**Comment by waszil** [comment]
It does! Thank you very much!
