### ISSUE TITLE
strict_map_keys for DataClassMessagePackMixin

### ISSUE THREAD

**Issue by Ryang20718** [Fatal1ty/mashumaro#237]
```
.from_msgpack(rf.read(), strict_map_key=False)
```

2.9 used to support `strict_map_key` false. Is there an equivalent in 3.13?

**Comment by Fatal1ty** [comment]
Yes, you can use “decoder” parameter. An example can be found in [this](https://github.com/Fatal1ty/mashumaro/blob/master/docs/2to3.md#changing-from_json-from_msgpack-from_yaml-signature) document.
