### ISSUE TITLE
can not use `datetime` as `datetime` directly when using `from_dict`

### ISSUE THREAD

**Issue by trim21** [Fatal1ty/mashumaro#241]
* mashumaro version: 3.13.1
* Python version: 3.12
* Operating System: win32

### Description

Describe what you were trying to get done.
Tell us what happened, what went wrong, and what you expected to happen.

### What I Did

I'm trying to convert a dict with `datetime` to dataclasses, without need of parsing, but it throw a error and says datetime instance is invalid as datetime

```
from dataclasses import dataclass
from datetime import UTC, datetime

from mashumaro import DataClassDictMixin


@dataclass(frozen=True, kw_only=True, slots=True)
class Obj(DataClassDictMixin):
    created_at: datetime


print(Obj.from_dict({"created_at": datetime.now(tz=UTC)}))
```

mashumaro.exceptions.InvalidFieldValue: Field "created_at" of type datetime in Obj has invalid value datetime.datetime(2024, 8, 31, 9, 47, 16, 474890, tzinfo=datetime.timezone.utc)

**Comment by Fatal1ty** [comment]
You need to use [pass_through](https://github.com/Fatal1ty/mashumaro?tab=readme-ov-file#passing-field-values-as-is) strategy for either the field or the type.

**Comment by trim21** [comment]
thanks
