### ISSUE TITLE
Is it possible to serialise a dataclass-mixin within another dataclass-mixin?

### ISSUE THREAD

**Issue by casparvitch** [Fatal1ty/mashumaro#246]
I have not worked out how to serialise a mixin that is *within* another mixin.
I feel that I am missing something in the docs and other issues, so reaching out for help :)

Example code that *works*:

```python
from mashumaro.mixins.msgpack import DataClassMessagePackMixin
from dataclasses import field, dataclass
import numpy as np
import numpy.typing as npt
import pickle

@dataclass
class ArrayMessage(DataClassMessagePackMixin):
    ar: npt.NDArray = field(
        metadata={"serialize": pickle.dumps, "deserialize": pickle.loads}
    )

test_ar = ArrayMessage(np.array([1, 2, 3]))
bytes = test_ar.to_msgpack()
print(bytes)
```
(pretty straightforward)

Now I want to msgpack an ArrayMessage inside another mixin:

```python
@dataclass
class FancyMessage(DataClassMessagePackMixin):
    name: str
    map: dict # <- want this to contain an ArrayMessage value, for example

fancy_message = FancyMessage("foo", {"ar": ArrayMessage(np.array([1, 2, 3]))})
new_bytes = fancy_message.to_msgpack() # ERROR
print(new_bytes)
```
This errors with `TypeError: can not serialize 'ArrayMessage' object`.

Much appreciated and thanks for the fabulous package 🙏!

**Comment by Fatal1ty** [comment]
Hi @casparvitch. Yes, you can. You just need to specify a more precise field type:
```python
@dataclass
class FancyMessage(DataClassMessagePackMixin):
    name: str
    map: dict[str, ArrayMessage]

fancy_message = FancyMessage("foo", {"ar": ArrayMessage(np.array([1, 2, 3]))})
new_bytes = fancy_message.to_msgpack()
print(new_bytes)
```

**Comment by casparvitch** [comment]
Thanks for the very quick response!

I wanted the FancyMessage to have many types in the map dict values, which is why I left it general.
If anyone else has a similar problem, see the below for a (very simple) solution:

```python
@dataclass
from typing import Any

class FancyMessage(DataClassMessagePackMixin):
    name: str
    map: dict[str, ArrayMessage | Any]
```

Much appreciated :pray:
