### ISSUE TITLE
Exclude certain attributes from serialization

### ISSUE THREAD

**Issue by sdb9696** [Fatal1ty/mashumaro#264]
**Is your feature request related to a problem? Please describe.**
I'm struggling to find an easy way to exclude certain attributes from serialization.

I may have missed something from the docs so apologies, but the only way I seem to have been able to do this is with a combination of a custom `SerializationStrategy` and `__pre_serialize__` hook. The attribute I'm looking to exclude is not serializable, so without the `SerializationStrategy` I get an `UnserializableField` error in the `UnpackRegistry.get`. Then I  found I needed the hook to prevent the attribute being serialized as `http_client: None`.

This is what I have:

```py
class _DoNotSerialize(SerializationStrategy):
    def serialize(self, value: Any) -> None:
        return None  # pragma: no cover

    def deserialize(self, value: Any) -> None:
        return None  # pragma: no cover

	# The attribute I want to exclude
    http_client: ClientSession | None = field(
        default=None,
        compare=False,
        metadata=field_options(serialization_strategy=_DoNotSerialize()),
    )

    def __pre_serialize__(self) -> Self:
        return replace(self, http_client=None)
```

**Describe the solution you'd like**
I'd like to be able to exclude an attribute from serialization with something like `field_options(exclude=True)`

**Describe alternatives you've considered**
Well I have the solution above but it's rather a lot for this simple use case.

**Additional context**
Apologies if I've missed something obvious but I really couldn't find out how to do this simply in the docs.

**Comment by Fatal1ty** [comment]
You can use “omit” word to exclude the field: https://github.com/Fatal1ty/mashumaro?tab=readme-ov-file#serialize-option

**Comment by sdb9696** [comment]
It was indeed `deserialize=passthrough` that got it working (I had previously tried `serialize="omit"` but that gives an error without passthrough)

Many thanks!
