### ISSUE TITLE
Unhashable type list due to wrong import statement

### ISSUE THREAD

**Issue by Enolerobotti** [Fatal1ty/mashumaro#270]
* mashumaro version: 3.15
* Python version: 3.9
* Operating System: Rhel 9

### Description

During an attempt to import mashumaro package I got
`TypeError: unhashable type: 'list'`

### What I Did

More precisely the error comes from here
`python ~/.local/lib/python3.9/site-packages/mashumaro/types.py`

It happens because class `Callable` was imported from `collections.abc` but not from the `typing` module.

I had to downgrade it to version 3.14.

**Comment by Fatal1ty** [comment]
The class collections.abc.Callable exists in python 3.9: https://docs.python.org/3.9/library/collections.abc.html#collections.abc.Callable
I can’t reproduce it.

**Comment by Fatal1ty** [comment]
Please, double check that you are on the latest Python 3.9 version.
