### ISSUE TITLE
Provide options to to_dict and from_dict calls.

### ISSUE THREAD

**Issue by gshank** [Fatal1ty/mashumaro#32]
We have callouts that we use in our 'from_dict' and 'to_dict' calls that sometimes need to run some transformations and sometimes can't run the transformations. It's difficult to give them information on which case is correct for this particular call without the ability to pass options along to the callouts. One way to do that would be to allow an 'options' dictionary on to_dict and from_dict that is passed to pre/post serialize/deserialize calls.

**Comment by Fatal1ty** [comment]
Why don't use hooks? Сan you show an example in which the hooks wouldn't be enough?

**Comment by Fatal1ty** [comment]
Theoretically, I could add a flag in the field / datacalss config to specify whether such options should be passed to the hook calls somehow. This flag could be turned off by default just to maintain better performance in most cases when the options aren't needed.

**Comment by gshank** [comment]
The main thing we use this for is a flag to indicate whether the 'to_dict' output would skip attributes that are set to 'None'. I though that an 'options' dictionary would be more flexible in that we could implement other options. Another thing that we need in a couple of places is converting field names to and from names with hyphens and underscores. At the moment either an options dictionary or an 'omit_none' or 'keep_none' flag would handle our requirements.

**Comment by Fatal1ty** [comment]
Seems like `omit_none` flag sounds reasonable. I'll try my best to add it soon.

**Comment by Fatal1ty** [comment]
@gshank I'm working on the configuration class that can change the code generation by adding `omit_none` flag to `to_dict` method signature. It's not the final version but you can test it: https://github.com/Fatal1ty/mashumaro/tree/config-class

```python
from typing import Optional
from mashumaro import DataClassDictMixin
from mashumaro.config import TO_DICT_ADD_OMIT_NONE_FLAG

class BaseModel(DataClassDictMixin):
    class Config:
        code_generation_options = [
            TO_DICT_ADD_OMIT_NONE_FLAG,
        ]

class Model(BaseModel):
    a: Optional[str] = None

print(Model().to_dict(omit_none=True))  # {}
```

**Comment by gshank** [comment]
Thanks! I'll take a look. If you're interested I put the code that I was using into https://github.com/gshank/mashumaro/tree/callout_options. Your method might be better though.

**Comment by gshank** [comment]
I did a few tests and it looks good.

**Comment by Fatal1ty** [comment]
These changes are in master branch already, so I close this issue.
