### ISSUE TITLE
String fields nether validated nor casted

### ISSUE THREAD

**Issue by Tishka17** [Fatal1ty/mashumaro#45]
I am decalring class with str field. I expect, that after parsing it will contain only str data. Possibilites are: cast any other types to str or raise a validation error during parsing. None of this happends

E.G, this code works and `obj.id` will be a `list` though it is declared as `str`

```python

@dataclass
class MashumaroTodo(DataClassDictMixin):
    id: str


obj = MashumaroTodo.from_dict({"id": ["invalid data"]})
```

**Comment by Fatal1ty** [comment]
https://github.com/Fatal1ty/mashumaro/issues/42
