### ISSUE TITLE
Error when trying pip install

### ISSUE THREAD

**Issue by chantinghin0203** [Fatal1ty/mashumaro#5]
Hello,

I encounter this issue when using pip install

    long_description=open('README.md').read(),
    UnicodeDecodeError: 'cp950' codec can't decode byte 0xe3 in position 13: illegal multibyte sequence

Please try to make all computer be able to install this package.

Thank you so much!

**Comment by Fatal1ty** [comment]
Hello, @chantinghin0203 

Could you tell me what operation system, python version and pip version you used to install the package?

**Comment by chantinghin0203** [comment]
Window 10
pip ==19.0.3
python==3.6

**Comment by chantinghin0203** [comment]
It is working! Well done buddy!

**Comment by Fatal1ty** [comment]
It’s great. Thanks for your participating.
