### ISSUE TITLE
How to omit a field on `from_dict`

### ISSUE THREAD

**Issue by johnsturgeon** [Fatal1ty/mashumaro#51]
I am de-serializing a dictionary from a MongoDB query, and I want to dis-regard the `_id` field on the incoming record.  Is there a way to do that?

**Comment by Fatal1ty** [comment]
@johnsturgeon Have you tried to pass a dictionary with `_id` key to the `from_dict` method of of a dataclass without `_id` field? There should be no problems.

**Comment by johnsturgeon** [comment]
LOL.. I have not, so it automatically ignores them?  Fantastic!

**Comment by Fatal1ty** [comment]
> so it automatically ignores them?

Yes, it does
