### ISSUE TITLE
How can I flag attributes as being 'ignored' on both serialize and deserialize

### ISSUE THREAD

**Issue by johnsturgeon** [Fatal1ty/mashumaro#52]
I only want attributes to be ephemeral .  I want to have them as part of the data class, but only used at run time, and I don't want them serialized.

How can I do that?

**Comment by Fatal1ty** [comment]
You can use [hooks](https://github.com/Fatal1ty/mashumaro#serialization-hooks) to exclude attributes from a dictionary or mark the fields as [init-only variables](https://docs.python.org/3/library/dataclasses.html#init-only-variables).

**Comment by johnsturgeon** [comment]
Ultimately I did end up using 'hooks', I used a post serialization hook to exclude my ivars from the resulting dict:
```python
  def __post_serialize__(self, d: Dict[Any, Any]) -> Dict[Any, Any]:
        d.pop('kills')
        d.pop('wins')
        d.pop('damage')
        return d
```

**Comment by Fatal1ty** [comment]
You can also use `__pre_deserialize__` hook and fields with defaults if you want to skip specific keys on deserializarion.
