### ISSUE TITLE
generate schema from models?

### ISSUE THREAD

**Issue by hampsterx** [Fatal1ty/mashumaro#55]
is there any way to generate a data dict of the model structure (field + type)? This would allow to generate typescript definitions for example ala poor mans openAPI generator type tool?

**Comment by Fatal1ty** [comment]
Hi. There is [get_type_hints](https://docs.python.org/3/library/typing.html#typing.get_type_hints) function you can use for this.

**Comment by hampsterx** [comment]
ahh thats true, yeah I had a quick look into your code afterwards and realised it should be quite straightforward. Cheers~

**Comment by Fatal1ty** [comment]
> Are there any plans for a non "poor mans" version? Or is there a compatible library that can generate jsonschema from a data class?

Unfortunately, I don't know of any compatible library but you could try to reuse [field metadata](https://docs.python.org/3/library/dataclasses.html#dataclasses.field) to generate a simple json schema.

> In the same vein, is there any plan to express types like `{"type": "string", "pattern": "someregex"}` which is a part of jsonschema?

To do this we need extensible validation mechanism which is not ready yet.
