### ISSUE TITLE
Serializing any type via cattrs-like structure/unstructure

### ISSUE THREAD

**Issue by fbergroth** [Fatal1ty/mashumaro#57]
Hi, thanks for a great library!

A lot of field types are supported, is there a reason they can't be serialized on their own?
I would be nice to be able to do this:

```
mashumaro.structure({"test": 4}, collections.Counter[str])
mashumaro.unstructure(my_list_of_named_tuple_instances)
```

**Comment by Fatal1ty** [comment]
Hello.

It's not easy to implement this feature right now, but I'll come back to this question after refactoring.

**Comment by fbergroth** [comment]
> Honestly, I don't like this idea

I don't see any drawbacks of this lib being a more general serialization library rather than just for dataclasses. I don't know what you don't like, but I'll close the issue then.
