### ISSUE TITLE
Feature Request: Optional Serde By Alias

### ISSUE THREAD

**Issue by micah-williamson** [Fatal1ty/mashumaro#58]
Hello I have a feature request that would be very beneficial to us. We are moving models in and out of a document store where attributes contribute to the size of the document. Because of this we want to shorten attributes when saving the document and rehydrate them coming out.

But there are places in our application where we don't have access to the deserialized dataclass and instead just have a dict. We want to abstract this so we don't have to know what the aliased fields are when working directly against a dict, and instead would like to have the ability to deserialize the dict based on either the alias or the unaliased keys.

**FEATURE REQUEST: MIXED ALIAS DESERIALIZATION**

Here is an example of a case where I'd like to build a new user entity from a dict. Then I'd like to deserialize it into my UserEntity. But while building my new user dict I don't want to have to know what the aliased fields are:
```
@dataclass
class UserEntity(DataClassDictMixin):
  name: str = field(metadata=field_options(alias="n"))
  age: str = field(metadata=field_options(alias="a"))

new_user = { "name": "Bill", "age": 30 }
new_user_ent = UserEntity.from_dict(new_user)
```

This doesn't work with DataClasDictMixin as far as I'm aware, so we created a helper mixin that translates unaliased fields to aliased fields before deserializing in the `__pre_deserialization__` method:

```
ALLOW_UNALIASED_DESERIALIZATION = True

@classmethod
def __pre_deserialize__(cls, d: Dict[Any, Any]) -> Dict[Any, Any]:
    if cls.ALLOW_UNALIASED_DESERIALIZATION:
        alias_revmap = cls.get_alias_revmap()
        for field, alias in alias_revmap.items():
            if field in d:
                d[alias] = d[field]
                d.pop(field)
    return d

@classmethod
def get_alias_map(cls) -> Dict[str, str]:
    """
    If aliases are defined. Returns a map of the aliased fields to the non-aliased field names
    """
    if not hasattr(cls, "__alias_map__"):
        cls.__alias_map__ = {}
        for key, field in cls.__dataclass_fields__.items():
            alias = field.metadata.get("alias")
            if alias:
                cls.__alias_map__[alias] = key
    return cls.__alias_map__

@classmethod
def get_alias_revmap(cls) -> Dict[str, str]:
    """
    If aliases are defined. Returns a map of the non-aliased fields to the alias field names
    """
    if not hasattr(cls, "__alias_revmap__"):
        alias_map = cls.get_alias_map()
        cls.__alias_revamp__ = {
            v: k for k, v in alias_map.items()
        }
    return cls.__alias_revamp__
```

**FEATURE REQUEST: OPTIONALLY DISABLE ALIAS SERIALIZATION**

When serializing entities, aliases are not used by default. Once again we have a situation where we'd like to optionally opt out of alias serialization. This can be done with the `TO_DICT_ADD_BY_ALIAS_FLAG`, but perhaps an oversight is that you cannot make alias serialization the default and the _opt out_ of it. If it is optional, it's only _opt in_.

```
@dataclass
class MyEntity(DataClassDictMixin):
    a: str = field(metadata=field_options(alias="FieldA"))
    b: str = field(metadata=field_options(alias="FieldB"))

    class Config(BaseConfig):
        serialize_by_alias = True
        code_generation_options = [TO_DICT_ADD_BY_ALIAS_FLAG]


def scratch():
    me = MyEntity(
        a="Hello",
        b="World"
    )
    print(me.to_dict())
    print(me.to_dict(by_alias=False))


if __name__ == "__main__":
    scratch()
```

In this sample I would expect `print(me.to_dict())` to use aliases during serialization, and for `print(me.to_dict(by_alias=False))` to opt out of the default. But even though I set the `serialize_by_alias` flag it will still use the unaliased fields during serialization because I've also added the `TO_DICT_ADD_BY_ALIAS_FLAG`.

I tried removing the `TO_DICT_ADD_BY_ALIAS_FLAG` entirely, but when you do that you no longer have access to `by_alias` in the `to_dict()` and it will throw this exception:

```
to_dict() got an unexpected keyword argument 'by_alias'
```

I tried to get around this by overwriting the `to_dict` method in both my helper mixin and entity class, but that code never gets hit.

```
    def to_dict(self, **kwargs) -> dict:
        print("HERE")
        return super().to_dict(**kwargs)
```

Whether as an instance method or a class method.

---

Thank you for taking the time to read through my feature request.

**Comment by Fatal1ty** [comment]
Hi 👋 Thank you for the detailed description. I’ll look closer to it after my vacation finished when I’m back to work. Thank you for understanding.

**Comment by Fatal1ty** [comment]
Hi @micah-williamson 

I made some changes in a [develop](https://github.com/Fatal1ty/mashumaro/tree/develop) branch so that the default value for `by_alias` argument of the `to_dict` method now depends on whether `serialize_by_alias` config option enabled.

**Comment by micah-williamson** [comment]
Thank you @Fatal1ty 

Could you also provide support for passing kwargs to serialization strategies (PROPAGATE_KWARGS)? We use this to change our serialization strategy based on the target. i.e. We want to serialize an model containing datetime into unix timestamp for one destination, but an iso formatted string in another.

**Comment by Fatal1ty** [comment]
> We want to serialize a model containing datetime into unix timestamp for one destination but then into an iso formatted string for another.

Is it possible to use two different dataclasses in your case?
```python
from dataclasses import dataclass
from datetime import datetime
from mashumaro import DataClassDictMixin
from mashumaro.config import BaseConfig

class TimestampMixin:
    class Config(BaseConfig):
        serialization_strategy = {
            datetime: {
                "serialize": lambda dt: dt.timestamp()
            }
        }

@dataclass
class BaseClass(DataClassDictMixin):
    dt: datetime

@dataclass
class CustomClass(BaseClass, TimestampMixin):
    pass

obj = BaseClass(datetime.utcnow())
print(obj.to_dict())
obj = CustomClass(datetime.utcnow())
print(obj.to_dict())
```

**Comment by micah-williamson** [comment]
Not without copying all of the properties of the dataclass into two others or skipping mashumaro altogether to implement some custom serializer.

Example:

We want to deserialize dicts into CDCRecords then serialize them differently depending on the destination. One data store uses Unix timestamps and the other uses iso formatted timestamps.

```
cdc_record = CDCRecord.from_dict(cdc_dict)

# Iso formatted timestamps
rds_update = cdc_record.to_dict(dialect=Dialect.RDS)

# Unix timestamps
ddb_update = cdc_record.to_dict(dialect=Dialect.DDB)
```

Having all of this configuration build into the serde definition of the model would be the most straightforward approach.

**Comment by Fatal1ty** [comment]
I like the idea of dialects. I can add a new `Dialect` abstraction that could be a place to override serialization / deserialization per type.
```python
from dataclasses import dataclass
from datetime import datetime
from mashumaro import DataClassDictMixin
from mashumaro import Dialect

class DDBDialect(Dialect):
    datetime = {
        "serialize": lambda dt: dt.timestamp(),
        "deserialize": lambda t: datetime.utcfromtimestamp(t),
    }
    
@dataclass
class MyClass(DataClassDictMixin):
    dt: datetime

obj = MyClass(datetime.utcnow())
print(obj.to_dict())  # will use the default serialization
print(obj.to_dict(dialect=DDBDialect))  # will use timestamps for datetime
```

**Comment by micah-williamson** [comment]
I think that will work. So will dialect overrides be based on data type? Will properties in the Dialect class be type of SerializationStrategy?

**Comment by Fatal1ty** [comment]
> So will dialect overrides be based on data type?

Yes, a custom dialect will have serialization and deserialization definitions for arbitrary types that you want to handle differently than in the default implementation (default dialect).

> Will properties in the Dialect class be type of SerializationStrategy?

They could be interpreted in a similar way to how it is done in a [`serialization_strategy`](https://github.com/Fatal1ty/mashumaro#serialization_strategy-config-option) config option. So, you can override what you need the way you need it.

**Comment by micah-williamson** [comment]
I think that will work. We are using Arrow for datetimes. So I can do something like this:

```
class BaseArrowSerializationStrategy(ABC, SerializationStrategy):

    @abstractmethod
    def serialize(self, value: Arrow) -> any:
        raise NotImplementedError()

    def deserialize(self, value: str) -> datetime:
        return arrow.get(value)
        
class ISOArrowSerializationStrategy(BaseArrowSerializationStrategy):

   def serialize(self, value: Arrow) -> str:
        return value.isoformat()
        
class UnixArrowSerializationStrategy(BaseArrowSerializationStrategy):

   def serialize(self, value: Arrow) -> int:
        return value.timestamp()

```

then:

```
@dataclass
class MyClass(DataClassDictMixin):
    dt: Arrow

obj = MyClass(arrow.utcnow())
print(obj.to_dict())  # will use the default serialization
print(obj.to_dict(dialect=ISOArrowSerializationStrategy))
print(obj.to_dict(dialect=UnixArrowSerializationStrategy))
```

And then I guess I can use either for deserializing.

**Comment by Fatal1ty** [comment]
> Though I don't know how you'd figure the property "arrow" means an Arrow type.

As I said before, a dialect will define serialization / deserialization for an arbitrary type:
```python
class DDBDialect(Dialect):
    Arrow = UnixArrowSerializationStrategy()
  
class RDSDialect(Dialect):
    Arrow = ISOArrowSerializationStrategy()
```

But since the dataclass uses third-party `Arrow` field type, it may be required to define a default implementation in a Config class or in the field metadata.

**Comment by micah-williamson** [comment]
```
class DDBDialect(Dialect):
    Arrow = UnixArrowSerializationStrategy()
```

Looks like you might run into an issue with `Arrow` not being in the locals though if you are trying to resolve type from a properties _name_.

Interested to see what you come up with!

**Comment by Fatal1ty** [comment]
> Looks like you might run into an issue with `Arrow` not being in the locals though if you are trying to resolve type from a properties _name_.

Ah, I see what you mean. It could be written as follows then:
```python
class DDBDialect(Dialect):
    types = {
        Arrow = UnixArrowSerializationStrategy()
    }
```

**Comment by Fatal1ty** [comment]
@micah-williamson you can check dialects in [this](https://github.com/Fatal1ty/mashumaro/tree/dialects) branch. It hasn't been tested yet, but you can help with that. With `datetime` instead of `Arrow` it could be written as follows:
```python
from dataclasses import dataclass
from datetime import datetime
from mashumaro import DataClassDictMixin
from mashumaro.config import ADD_DIALECT_SUPPORT, BaseConfig
from mashumaro.dialect import Dialect
from mashumaro.types import SerializationStrategy

class ISOSerializationStrategy(SerializationStrategy):
    def serialize(self, value: datetime) -> str:
        return value.isoformat()

class UnixSerializationStrategy(SerializationStrategy):
    def serialize(self, value: datetime) -> float:
        return value.timestamp()

class DDBDialect(Dialect):
    serialization_strategy = {
        datetime: UnixSerializationStrategy()
    }

class RDSDialect(Dialect):
    serialization_strategy = {
        datetime: ISOSerializationStrategy()
    }

@dataclass()
class MyClass(DataClassDictMixin):
    datetime: datetime

    class Config(BaseConfig):
        code_generation_options = [ADD_DIALECT_SUPPORT]
        # dialect = DDBDialect  # default dialect

obj = MyClass(datetime.utcnow())
print(obj.to_dict())  # will use the default dialect
print(obj.to_dict(dialect=DDBDialect))
print(obj.to_dict(dialect=RDSDialect))
```

**Comment by Fatal1ty** [comment]
@micah-williamson I added support for dialects in 2.10. You can give it a go.
Since this thread became the place to discuss different things I'm going to close this issue.

**Comment by micah-williamson** [comment]
Thanks @Fatal1ty - I'll try this out soon (probably next week).
