### ISSUE TITLE
Remapping json output and input

### ISSUE THREAD

**Issue by chantinghin0203** [Fatal1ty/mashumaro#6]
Is the function of remapping of the input and output of the JSON is supported?

I see dict_param but it does not work as expected.

@dataclass
class User(DataClassJSONMixin):
    id: int
    username: str
    email: str

assert User.from_json(json.dumps({"ID":1})) == User(id=1) # FAILED

**Comment by Fatal1ty** [comment]
There is no such option, but you can pass a decoder which will remap keys based on your rules. You can see an example I've added to the repository:
https://github.com/Fatal1ty/mashumaro/blob/master/examples/json_remapping.py

**Comment by chantinghin0203** [comment]
Thank you for your reply. It works but I feel like there should be a more elegant way to do it. Is it possible to add a checking directly in the base class which checks if there is __remapping__ specified.

**Comment by Fatal1ty** [comment]
I can think about it but could you tell me what you need it for?

**Comment by chantinghin0203** [comment]
For example, if I got a json from some API which has the following format:

{
"ID":13,
"Name":"James",
"Address-No":"ABC 132"
}

I would like to define the model with field as snake case instead of "ID", "Name" and "Address-No". 
Moreover, in this case, I cannot even map the json with field "Address-No" as it is illegal syntax in python

**Comment by Fatal1ty** [comment]
Thanks for the example. I see, this enhancement would be helpful in such cases. I will think of a better way to do it. You could use a custom decoder and encoder until then.

**Comment by Fatal1ty** [comment]
@chantinghin0203 with the new version, you can do this via a hook:
```python
@dataclass
class User(DataClassJSONMixin):
    id: int
    name: str
    address_no: str

    @classmethod
    def __pre_deserialize__(cls, d: Dict[Any, Any]) -> Dict[Any, Any]:
        return {
            "id": d["ID"],
            "name": d["Name"],
            "address_no": d["Address-No"],
        }


d = {"ID": 13, "Name": "James", "Address-No": "ABC 132"}
print(User.from_dict(d))  # User(id=13, name='James', address_no='ABC 132')
```

I hope it could help. Also I'm thinking of adding `alias` like field options to the existing ones https://github.com/Fatal1ty/mashumaro#field-options. Let's keep this issue opened for now.

**Comment by chantinghin0203** [comment]
It looks nice. Thanks

**Comment by Fatal1ty** [comment]
It can be done with [serialization hooks](https://github.com/Fatal1ty/mashumaro#serialization-hooks) since 1.20 is released.

**Comment by Fatal1ty** [comment]
@chantinghin0203 I added support for aliases, you can see examples in updated [README](https://github.com/Fatal1ty/mashumaro/blob/master/README.md) and in [the pull request](https://github.com/Fatal1ty/mashumaro/pull/46#issue-610140549). I think it's time to close this issue :)
