### ISSUE TITLE
`TypeError` using PEP-585 standard collection annotation types  for Python <3.9

### ISSUE THREAD

**Issue by FrancescoCasalegno** [Fatal1ty/mashumaro#65]
## Summary

In the [release v2.8](https://github.com/Fatal1ty/mashumaro/releases/tag/v2.8) of `mashumaru` one of the updates includes support for [PEP 585](https://www.python.org/dev/peps/pep-0585/) compliance.

This implies supporting type annotations using the standard collection types `list`, `tuple`, ... instead of the corresponding generics `typing.List`, `typing.Tuple`, ...

However, on `Python 3.7` or `Python 3.8` a `TypeError` is raised.

## Reproduce the Error 

The following code snippet
```python
from __future__ import annotations
from mashumaro import DataClassJSONMixin

# This works fine
x: list[int] = [1, 2, 3]
print(x)

# This raises TypeError on Python <3.9
class MyClass(DataClassJSONMixin):
    arg1: list[int]
```

runs without issues on `Python 3.9`, but produces an error on `Python 3.7` and  and `Python 3.8`:
```python
TypeError: 'type' object is not subscriptable
```

## Environment
- Operating System: `Mac OS X`
- `mashumaro` Version: `2.10.1`
- Python Versions: `3.7.6`, `3.8.1`, `3.9.1`

**Comment by Fatal1ty** [comment]
Hi @FrancescoCasalegno 

The new syntax introduced in [PEP 585](https://www.python.org/dev/peps/pep-0585/) works on source level only for 3.9+. On older versions this syntax with `from __future__ import annotations` only works for annotations that is simply not enough for mashumaro.

See here for details: https://www.python.org/dev/peps/pep-0585/#backwards-compatibility

**Comment by FrancescoCasalegno** [comment]
I see, thank you very much for the prompt answer @Fatal1ty !
I guess we can close this Issue.
