### ISSUE TITLE
Please add a Changelog

### ISSUE THREAD

**Issue by klamann** [Fatal1ty/mashumaro#72]
I couldn't find any information in the Readme about any breaking changes in the 3.0 release and there does not appear to be a changelog. Can you add a CHANGELOG.md file that contains the most important updates as well as a list of breaking changes for every release?

I like the format proposed by https://keepachangelog.com

**Comment by Fatal1ty** [comment]
Hi @klamann 

I'm sorry that you might have had to face backwards incompatible changes during update to 3.0.

This project supports https://semver.org, so breaking changes could be introduced in subsequent major versions only. To avoid problems, you could freeze the major version of a dependency. it's considered good practice. You can find details in [PEP 440](https://www.python.org/dev/peps/pep-0440/#compatible-release).

Changelog has been published on [Github Releases page](https://github.com/Fatal1ty/mashumaro/releases). Release 3.0 has "Backward incompatible changes" section with a link to the migration guide. I thought it would help to deal with all breaking changes.

I can add CHANGELOG.md but I don't like the idea of writing changes in two places. If you can tell me how to keep GitHub Releases in sync with CHANGELOG.md, it would save me a lot of time.

**Comment by klamann** [comment]
Hi @Fatal1ty, I didn't notice the GitHub Releases page, that's what I have been looking for, thanks!

The Changelog on the Releases page looks perfectly fine to me, I just had trouble finding it in the usual places (on pypi, in the readme, changelog.md, etc.). Can you maybe add a Changelog section to the Readme and link to the GitHub Releases page from there? Keywords I was looking for in the Readme are "Changelog", "changes", "breaking", but there were no relevant matches.

**Comment by Fatal1ty** [comment]
> Can you maybe add a Changelog section to the Readme and link to the GitHub Releases page from there?

That sounds reasonable. I'll see how to make it better.

**Comment by Fatal1ty** [comment]
Fixed: https://github.com/Fatal1ty/mashumaro#changelog
