### ISSUE TITLE
Handling defaults in dataclasses

### ISSUE THREAD

**Issue by peku-jamf** [Fatal1ty/mashumaro#74]
QUESTION

When it comes to default values in dataclasses, is there any documentation how it should be handled properly? Unfortunately I haven't found anything related.

e.g. I have my schema below:

```
@dataclass
class LogLevel(DataClassYAMLMixin):
    level: str = field(default="INFO")

@dataclass
class Config(DataClassYAMLMixin):
    logging: LogLevel

```
yaml file:
```
logging:


```

there is no log level defined in yaml, only 'logging' section, so expected dataclass will be created using defaults, but it's not.

```
Class: MyServiceClass, Mq(mq=MqSetup(setup=1, setup2='neco')), Config(logging=None)
```
instead of:
```
Class: MyServiceClass, Mq(mq=MqSetup(setup=1, setup2='neco')), Config(logging=LogLevel(level='INFO'))
```

Can this usecase be handled by mashumaro library, please?

**Comment by Fatal1ty** [comment]
Given your input:
```yaml
logging:
```
YAML Loader produces `{"logging": None}` that is not correct for your `Config` scheme. Leaving the value blank means not an empty mapping but null. You should change it this way:
```yaml
logging: {}
```

If for some reason you want to break the rules, you can handle this by the hook:
```python
@dataclass
class Config(DataClassYAMLMixin):
    logging: LogLevel

    @classmethod
    def __pre_deserialize__(cls, d):
        if d.get('logging') is None:
            d['logging'] = {}
        return d


s = 'logging:'
config = Config.from_yaml(s)
print(config)  # Config(logging=LogLevel(level='INFO'))
```

**Comment by peku-jamf** [comment]
amazing, thanks for the clarification!
