### ISSUE TITLE
What is the difference between mashumaro.mixins.msgpack.DataClassMessagePackMixin and mashumaro.serializer.msgpack.DataClassMessagePackMixin?

### ISSUE THREAD

**Issue by Gwill** [Fatal1ty/mashumaro#77]
What is the difference between `mashumaro.mixins.msgpack.DataClassMessagePackMixin` and `mashumaro.serializer.msgpack.DataClassMessagePackMixin`?

**Comment by Fatal1ty** [comment]
Hi @Gwill

`DataClassMessagePackMixin` has been moved from `mashumaro.serializer.msgpack.DataClassMessagePackMixin` to `mashumaro.mixins.msgpack.DataClassMessagePackMixin` in 3.0. The difference is in the signature of `from_msgpack` / `to_msgpack` methods. See this guide for details: https://github.com/Fatal1ty/mashumaro/blob/master/docs/2to3.md
