### ISSUE TITLE
Passing arguments to yaml dumper

### ISSUE THREAD

**Issue by marcelloDC** [Fatal1ty/mashumaro#84]
Hi Fatal1ty,

Thanks for writing this great module! I have one question/request. By default, pyYaml sorts dictionaries by keyword and doesn't allow unicode. Before, I got around this by setting the two relevant parameters 'allow_unicode' and 'sort_keys' when calling the dumper:
```
yaml.safe_dump(data, filehandle, allow_unicode=True, sort_keys=False)
```
Is there a way to achieve the same result with mashumaro when using the DataClassYAMLMixin ?

**Comment by Fatal1ty** [comment]
Hi @marcelloDC,

Yes, it can be achieved when using DataClassYAMLMixin. You can pass a custom encoder to `to_yaml` method:
```python
def custom_encoder(data) -> EncodedData:
    return yaml.safe_dump(data, filehandle, allow_unicode=True, sort_keys=False)

dataclass.to_yaml(encoder=custom_encoder)
```

**Comment by Fatal1ty** [comment]
I'm closing this issue since your question is answered. If you have any other questions, please open another issue.
