### ISSUE TITLE
TypeError: unhashable type: 'Pet'

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [Fatal1ty/mashumaro#9]
1. running the example from readme.md
https://github.com/Fatal1ty/mashumaro/blob/master/README.md#usage-example

2. produces an error
```
Traceback (most recent call last):
  File "/.../src/verify/code/mashu/mashu_json.py", line 29, in <module>
    john = Person(first_name='John', second_name='Smith', age=18, pets={tom, jerry})
TypeError: unhashable type: 'Pet'
```
3. on py 3.7
```
python --version
Python 3.7.3
```

**Comment by Fatal1ty** [comment]
Thanks! Keys of dictionary must be hashed, I just missed to add `unsafe_hash=True` into the `dataclass` decorator in the example.

**Comment by Fatal1ty** [comment]
Fixed.
